[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules','lib']
test = 'test/foundry'
cache_path = 'forge-cache'

[fuzz]
runs = 10
max_test_rejects = 1

gas_reports = ["*"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config